// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC75fmoTFaSnFDgCoOg02N-JBkMEKOW8sc',
    appId: '1:922916800011:web:4accafaafdc2e6ae3d690e',
    messagingSenderId: '922916800011',
    projectId: 'you-matter-8446c',
    authDomain: 'you-matter-8446c.firebaseapp.com',
    storageBucket: 'you-matter-8446c.appspot.com',
    measurementId: 'G-B34TPZSLYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDQxGUvwScW8W13Ea98q4jTouj7YbKUAA',
    appId: '1:922916800011:android:2b0425771170d9013d690e',
    messagingSenderId: '922916800011',
    projectId: 'you-matter-8446c',
    storageBucket: 'you-matter-8446c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN4xoTThKG2-AM2n92DeQqnKgGtuGxBj8',
    appId: '1:922916800011:ios:cae3b9e31ff09c0c3d690e',
    messagingSenderId: '922916800011',
    projectId: 'you-matter-8446c',
    storageBucket: 'you-matter-8446c.appspot.com',
    iosBundleId: 'com.example.youMatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN4xoTThKG2-AM2n92DeQqnKgGtuGxBj8',
    appId: '1:922916800011:ios:08e3e5415412c8b73d690e',
    messagingSenderId: '922916800011',
    projectId: 'you-matter-8446c',
    storageBucket: 'you-matter-8446c.appspot.com',
    iosBundleId: 'com.example.youMatter.RunnerTests',
  );
}
